services:
  mimir:
    image: grafana/mimir:2.8.0
    container_name: mimir
    ports:
      - 9090:9090
    restart: unless-stopped
    command: --config.file=/etc/mimir.yaml
    volumes:
      - ./services/mimir/mimir.yaml:/etc/mimir.yaml
      - ./services/mimir/alertmanager.yaml:/etc/alertmanager-fallback-config.yaml
  
  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      - JAEGER_AGENT_HOST=otelcol

  grafana:
    image: grafana/grafana:9.5.1
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_TRACING_OPENTELEMETRY_OTLP_ADDRESS=otelcol:4317
      - GF_TRACING_OPENTELEMETRY_OTLP_PROPAGATION=w3c
      - GF_FEATURE_TOGGLES_ENABLE=tempoBackendSearch,tempoSearch,tempoServiceGraph
    volumes:
      - ./services/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - loki
      - tempo
      - mimir

  tempo:
    image: grafana/tempo:2.1.1
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./services/tempo/tempo.yaml:/etc/tempo.yaml

  ## Tools
  promtail:
    image: grafana/promtail:2.5.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  otelcol:
    image: otel/opentelemetry-collector:0.76.1
    container_name: otelcol
    # restart: unless-stopped
    ports:
      - "14268:14268"  # jaeger ingest
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    command: --config=/etc/otelcol/config.yaml
    depends_on:
      - loki
      - tempo
      - mimir
      - grafana
    volumes:
      # - /var/run/docker.sock.raw:/var/run/docker.sock
      - ./services/otelcol/config.yaml:/etc/otelcol/config.yaml
